include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false       # Allow print statements for debugging
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true

